apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-service-nginx
spec:
  type: ClusterIP
  selector:
    project: {{.Release.Name}}
  ports:
    - name: http
      port: 80
      targetPort: 80
      #NodePort: 30000
   
