apiVersion: agroproj.io/v1alpha1
kind: Application
metadata:
  name: app-nginx
  namespace: argocd
  finalizers:
    - resources-funalizer.argocd.argoproj.io
spec:
  destination:
    name: app-nginx
    namespace: app-nginx
  source:
    path: "Chart" 
    repoURL: "git@github.com:Alex232001/connection-argo.git"
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: "image"
          value: nginx:latest   
   project: default
   syncPolicy:
     automated:
       prune: true
       selfHeal: true
     syncOptions:
       - CreateNamespace=true







